// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_rileyrm.Models;

namespace Mission06_rileyrm.Migrations
{
    [DbContext(typeof(MovieForumContext))]
    [Migration("20230220021359_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_rileyrm.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Superhero"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Documentary"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Romantic"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Thriller"
                        });
                });

            modelBuilder.Entity("Mission06_rileyrm.Models.MovieForumResponse", b =>
                {
                    b.Property<int>("MovieForumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieForumID");

                    b.HasIndex("CategoryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieForumID = 1,
                            CategoryID = 1,
                            Director = "James Mangold",
                            Edited = true,
                            LentTo = "none",
                            Notes = "Best superhero movie",
                            Rating = "R",
                            Title = "Logan",
                            Year = 2017
                        },
                        new
                        {
                            MovieForumID = 2,
                            CategoryID = 1,
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "none",
                            Notes = "Second best superhero movie",
                            Rating = "PG-13",
                            Title = "Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            MovieForumID = 3,
                            CategoryID = 2,
                            Director = "Edgar Wright",
                            Edited = true,
                            LentTo = "none",
                            Notes = "Like Fast and Furious but better",
                            Rating = "R",
                            Title = "Baby Driver",
                            Year = 2017
                        });
                });

            modelBuilder.Entity("Mission06_rileyrm.Models.MovieForumResponse", b =>
                {
                    b.HasOne("Mission06_rileyrm.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
